version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: Installing Build System
          command: |
            apt-get update
            apt-get install -y git build-essential cmake libcupsimage2-dev
            apt-get install -y autoconf automake autotools-dev libtool
            apt-get install -y libnss3-dev libcairo2-dev libopenjp2-7-dev libopenjp2-tools libopenjp2-7

      - checkout
      - run:
          name: Setup latest Poppler + CUPS
          command: |
            git clone https://github.com/freedesktop/poppler
            git clone https://github.com/mpsuzuki/cups
            cd cups
            git remote add upstream https://github.com/apple/cups
            git fetch upstream
            git rebase upstream/master

      - run:
          name: Build CUPS
          command: |
            cd cups
            ./configure --prefix=`pwd`/../root/
            make install INITDIR=`pwd`/../root/etc DBUSDIR=`pwd`/../root/etc/dbus-1 MENUDIR=`pwd`/../share/applications ICONDIR=`pwd`/../root/share/icons

      - run:
          name: Build Poppler
          command: |
            cd poppler
            cmake -DCMAKE_INSTALL_PREFIX=`pwd`/../root -H. -Bbuild -DENABLE_GLIB=OFF -DENABLE_QT5=OFF -DENABLE_UTILS=OFF -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
            make -C build
            make -C build install
            ( mkdir -p ../root/include/poppler/ && cd ../root/include/poppler/ && ln -s ../poppler . )

      - run:
          name: Build pdftoopvp
          command: |
            ./autogen.sh
            env PKG_CONFIG_PATH=`pwd`/root/lib/pkgconfig/ ./configure
            make
